name: megahack3
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  adobe_xd: ^0.1.4
  firebase_messaging: ^6.0.13
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  provider: ^4.0.5
  mask_text_input_formatter: ^1.0.7
  font_awesome_flutter:
  link: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/bg.jpg
    - assets/image/logo.png